import type { PaletteToken } from './types';

export default ((_dark) => ({
  borderRadius: 8,
  colorBorder: 'var(--color-divider)',
  colorLink: 'var(--color-primary)',
  colorLinkHover: 'var(--color-primary-80)',
  colorSplit: 'var(--color-divider)',

  colorBgBase: 'var(--color-content-base)',
  colorBgContainer: 'var(--color-content-paper)',
  colorBgContainerDisabled: 'var(--color-disabled-light)',
  colorBgElevated: 'var(--color-content-base)',
  colorBgLayout: 'var(--color-content-layout)',

  colorText: 'var(--color-contrast)',
  colorTextDisabled: 'var(--color-disabled-dark)',
  colorTextPlaceholder: 'var(--color-divider)',

  colorPrimary: 'var(--color-primary)',
  colorPrimaryActive: 'var(--color-muted)',
  colorPrimaryBg: 'var(--color-primary-40)',
  colorPrimaryBorder: 'var(--color-primary-60)',
  colorPrimaryBorderHover: 'var(--color-primary-60)',
  colorPrimaryHover: 'var(--color-primary-60)',
  colorPrimaryText: 'var(--color-primary)',
  colorPrimaryTextActive: 'var(--color-muted)',
  colorPrimaryTextHover: 'var(--color-primary-80)',

  colorError: 'var(--color-error-dark)',
  colorErrorActive: 'var(--color-muted)',
  colorErrorBg: 'var(--color-error-light)',
  colorErrorBorder: 'var(--color-error-divider)',
  colorErrorBorderHover: 'var(--color-error-divider)',
  colorErrorHover: 'var(--color-error-divider)',
  colorErrorText: 'var(--color-error)',
  colorErrorTextActive: 'var(--color-muted)',
  colorErrorTextHover: 'var(--color-error-light)',

  colorInfo: 'var(--color-info-dark)',
  colorInfoActive: 'var(--color-muted)',
  colorInfoBg: 'var(--color-info-light)',
  colorInfoBorder: 'var(--color-info-divider)',
  colorInfoBorderHover: 'var(--color-info-divider)',
  colorInfoHover: 'var(--color-info-divider)',
  colorInfoText: 'var(--color-info)',
  colorInfoTextActive: 'var(--color-muted)',
  colorInfoTextHover: 'var(--color-info-light)',

  colorSuccess: 'var(--color-success-dark)',
  colorSuccessActive: 'var(--color-muted)',
  colorSuccessBg: 'var(--color-success-light)',
  colorSuccessBorder: 'var(--color-success-divider)',
  colorSuccessBorderHover: 'var(--color-success-divider)',
  colorSuccessHover: 'var(--color-success-divider)',
  colorSuccessText: 'var(--color-success)',
  colorSuccessTextActive: 'var(--color-muted)',
  colorSuccessTextHover: 'var(--color-success-light)',

  colorWarning: 'var(--color-warning-dark)',
  colorWarningActive: 'var(--color-muted)',
  colorWarningBg: 'var(--color-warning-light)',
  colorWarningBorder: 'var(--color-warning-divider)',
  colorWarningBorderHover: 'var(--color-warning-divider)',
  colorWarningHover: 'var(--color-warning-divider)',
  colorWarningText: 'var(--color-warning)',
  colorWarningTextActive: 'var(--color-muted)',
  colorWarningTextHover: 'var(--color-warning-light)',

  cyan: '#13C2C2',
  geekblue: '#2F54EB',
  lime: '#A0D911',
  magenta: '#EB2F96',
  orange: '#FA8C16',
  purple: '#722ED1',
  volcano: '#FA541C',
})) satisfies PaletteToken;
