import type { AntdComponents } from './types';

export default {
  Badge: {
    colorError: 'var(--color-error-dark)',
    colorInfo: 'var(--color-info-dark)',
    colorPrimary: 'var(--color-primary)',
    colorSuccess: 'var(--color-success-dark)',
    colorWarning: 'var(--color-warning-dark)',
  },
  Button: {
    borderColorDisabled: 'var(--color-disabled-dark)',
    colorBgContainer: 'transparent',
    colorError: 'var(--color-error-dark)',
    colorPrimary: 'var(--color-primary)',
    defaultGhostBorderColor: 'var(--color-black)',
    defaultGhostColor: 'var(--color-black)',
    ghostBg: 'transparent',
  },
  Calendar: {
    colorBgContainer: 'var(--color-content-layout)',
    colorText: 'var(--color-black)',
  },
  Card: {
    headerBg: 'var(--color-content-base)',
    colorBgContainer: 'var(--color-content-layout)',
    colorBorderSecondary: 'var(--color-divider)',
    colorTextHeading: 'var(--color-primary)',
  },
  Checkbox: {
    colorBgContainer: 'var(--color-content-layout)',
    colorText: 'var(--color-primary)',
    colorPrimary: 'var(--color-primary)',
  },
  Collapse: {
    colorBgContainer: 'var(--color-content-layout)',
    colorText: 'var(--color-black)',
    colorTextHeading: 'var(--color-primary)',
    headerBg: 'var(--color-content-base)',
  },
  DatePicker: {
    activeBorderColor: 'var(--color-secondary)',
    cellHoverBg: 'var(--color-primary-20)',
    colorBgContainer: 'var(--color-content-layout)',
    colorBorder: 'var(--color-primary)',
    colorError: 'var(--color-error-dark)',
    colorInfo: 'var(--color-info-dark)',
    colorSuccess: 'var(--color-success-dark)',
    colorText: 'var(--color-black)',
    colorWarning: 'var(--color-warning-dark)',
    controlItemBgActive: 'var(--color-primary-20)',
    controlItemBgHover: 'var(--color-primary-20)',
    hoverBorderColor: 'var(--color-primary-20)',
  },
  Descriptions: {
    labelBg: 'var(--color-content-base)',
    labelColor: 'var(--color-gray)',
  },
  Divider: {
    colorTextHeading: 'var(--color-gray)',
    colorText: 'var(--color-gray)',
  },
  Empty: {
    colorTextDescription: 'var(--color-gray)',
  },
  Input: {
    activeBorderColor: 'var(--color-secondary)',
    colorBorder: 'var(--color-primary)',
    colorBgContainer: 'var(--color-content-layout)',
    colorError: 'var(--color-error-dark)',
    colorInfo: 'var(--color-info-dark)',
    colorSuccess: 'var(--color-success-dark)',
    colorText: 'var(--color-black)',
    colorWarning: 'var(--color-warning-dark)',
    hoverBorderColor: 'var(--color-primary-20)',
  },
  InputNumber: {
    activeBorderColor: 'var(--color-secondary)',
    colorBorder: 'var(--color-primary)',
    colorBgContainer: 'var(--color-content-layout)',
    colorError: 'var(--color-error-dark)',
    colorInfo: 'var(--color-info-dark)',
    colorSuccess: 'var(--color-success-dark)',
    colorText: 'var(--color-black)',
    colorWarning: 'var(--color-warning-dark)',
    hoverBorderColor: 'var(--color-primary-20)',
  },
  Layout: {
    headerBg: 'var(--color-secondary)',
  },
  Menu: {
    itemSelectedColor: 'var(--color-info-dark)',
    itemBg: 'var(--color-primary-20)',
    subMenuItemBg: 'var(--color-primary-10)',
    darkItemBg: 'var(--color-primary)',
    darkSubMenuItemBg: 'var(--color-primary-60)',
    darkPopupBg: 'var(--color-primary-90)',
    darkItemSelectedBg: 'var(--color-secondary)',
    subMenuItemSelectedColor: 'var(--color-orange-dark)',
  },
  Message: {
    colorBgElevated: 'var(--color-content-base)',
    colorError: 'var(--color-error-dark)',
    colorInfo: 'var(--color-info-dark)',
    colorPrimary: 'var(--color-primary)',
    colorSuccess: 'var(--color-success-dark)',
    colorWarning: 'var(--color-warning-dark)',
  },
  Notification: {
    colorBgElevated: 'var(--color-content-base)',
    colorError: 'var(--color-error-dark)',
    colorInfo: 'var(--color-info-dark)',
    colorPrimary: 'var(--color-primary)',
    colorSuccess: 'var(--color-success-dark)',
    colorWarning: 'var(--color-warning-dark)',
  },
  Pagination: {
    colorBgContainer: 'var(--color-content-layout)',
    colorBgTextHover: 'var(--color-primary-20)',
    colorBorder: 'var(--color-primary)',
    colorBorderSecondary: 'red',
    colorPrimary: 'var(--color-primary)',
    colorPrimaryHover: 'var(--color-primary-20)',
    colorText: 'var(--color-black)',
    itemActiveBg: 'var(--color-primary-10)',
    itemActiveColorDisabled: 'var(--color-black)',
    itemBg: 'transparent',
  },
  Radio: {
    colorBgContainer: 'var(--color-content-layout)',
    colorText: 'var(--color-primary)',
    colorPrimary: 'var(--color-primary)',
    buttonCheckedColorDisabled: 'var(--color-gray)',
  },
  Result: {
    colorError: 'var(--color-error-dark)',
    colorInfo: 'var(--color-info-dark)',
    colorPrimary: 'var(--color-primary)',
    colorSuccess: 'var(--color-success-dark)',
    colorWarning: 'var(--color-warning-dark)',
  },
  Spin: {
    colorPrimary: 'var(--color-secondary)',
  },
  Statistic: {
    colorTextDescription: 'var(--color-gray)',
    colorTextHeading: 'var(--color-primary)',
  },
  Select: {
    activeBorderColor: 'var(--color-secondary)',
    colorBorder: 'var(--color-primary)',
    colorError: 'var(--color-error-dark)',
    colorInfo: 'var(--color-info-dark)',
    colorSuccess: 'var(--color-success-dark)',
    colorText: 'var(--color-black)',
    colorWarning: 'var(--color-warning-dark)',
    hoverBorderColor: 'var(--color-primary-20)',
    selectorBg: 'var(--color-content-layout)',
  },
  Steps: {
    colorPrimary: 'var(--color-secondary)',
    colorText: 'var(--color-primary)',
    colorTextDescription: 'var(--color-gray)',
    controlItemBgActive: 'var(--color-secondary-20)',
  },
  Switch: {
    handleBg: 'var(--color-white)',
  },
  Table: {
    bodySortBg: 'var(--color-secondary-10)',
    colorBgContainer: 'var(--color-content-layout)',
    expandIconBg: 'var(--color-secondary-20)',
    headerBg: 'var(--color-content-base)',
    headerColor: 'var(--color-black)',
    headerSortActiveBg: 'var(--color-secondary-40)',
    headerSortHoverBg: 'var(--color-primary-40)',
    rowHoverBg: 'var(--color-disabled-light)',
    rowSelectedBg: 'var(--color-secondary-10)',
    rowSelectedHoverBg: 'var(--color-disabled-light)',
  },
  Tabs: {
    cardBg: 'var(--color-primary-20)',
    colorBgContainer: 'var(--color-content-layout)',
    colorBorderSecondary: 'var(--color-divider)',
    inkBarColor: 'var(--color-primary)',
    itemColor: 'var(--color-black)',
    itemHoverColor: 'var(--color-gray)',
    itemSelectedColor: 'var(--color-primary)',
  },
  Tag: {
    colorError: 'var(--color-error-dark)',
    colorErrorBg: 'var(--color-error-light)',
    colorErrorBorder: 'var(--color-error-divider)',
    colorInfo: 'var(--color-info-dark)',
    colorInfoBg: 'var(--color-info-light)',
    colorInfoBorder: 'var(--color-info-divider)',
    colorPrimary: 'var(--color-primary)',
    colorSuccess: 'var(--color-success-dark)',
    colorSuccessBg: 'var(--color-success-light)',
    colorSuccessBorder: 'var(--color-success-divider)',
    colorWarning: 'var(--color-warning-dark)',
    colorWarningBg: 'var(--color-warning-light)',
    colorWarningBorder: 'var(--color-warning-divider)',
    defaultBg: 'var(--color-light)',
    defaultColor: 'var(--color-gray)',
  },
  Tooltip: {
    colorBgSpotlight: 'var(--color-secondary)',
  },
  Typography: {
    colorError: 'var(--color-error-dark)',
    colorInfo: 'var(--color-info-dark)',
    colorSuccess: 'var(--color-success-dark)',
    colorText: 'var(--color-black)',
    colorTextDisabled: 'var(--color-disabled-dark)',
    colorTextHeading: 'var(--color-primary)',
    colorTextSecondary: 'var(--color-gray)',
    colorWarning: 'var(--color-warning-dark)',
  },
} satisfies AntdComponents;
