import type { AntdComponents } from './types';

export default {
  Badge: {
    colorError: 'var(--color-error-dark)',
    colorInfo: 'var(--color-info-dark)',
    colorPrimary: 'var(--color-primary)',
    colorSuccess: 'var(--color-success-dark)',
    colorWarning: 'var(--color-warning-dark)',
  },
  Button: {
    borderColorDisabled: 'var(--color-disabled-dark)',
    colorBgContainer: 'transparent',
    colorError: 'var(--color-error-dark)',
    colorPrimary: 'var(--color-primary)',
    defaultGhostBorderColor: 'var(--color-black)',
    defaultGhostColor: 'var(--color-black)',
    ghostBg: 'transparent',
  },
  Checkbox: {
    colorBgContainer: 'transparent',
    colorText: 'var(--color-primary)',
    colorPrimary: 'var(--color-primary)',
  },
  DatePicker: {
    activeBorderColor: 'var(--color-secondary)',
    cellHoverBg: 'var(--color-primary-20)',
    colorBgContainer: 'var(--color-content-layout)',
    colorBorder: 'var(--color-primary)',
    colorError: 'var(--color-error-dark)',
    colorInfo: 'var(--color-info-dark)',
    colorSuccess: 'var(--color-success-dark)',
    colorText: 'var(--color-black)',
    colorWarning: 'var(--color-warning-dark)',
    controlItemBgActive: 'var(--color-primary-20)',
    controlItemBgHover: 'var(--color-primary-20)',
    hoverBorderColor: 'var(--color-primary-20)',
  },
  Divider: {
    colorTextHeading: 'var(--color-gray)',
    colorText: 'var(--color-gray)',
  },
  Empty: {
    colorTextDescription: 'var(--color-gray)',
  },
  Input: {
    activeBorderColor: 'var(--color-secondary)',
    colorBorder: 'var(--color-primary)',
    colorBgContainer: 'var(--color-content-layout)',
    colorError: 'var(--color-error-dark)',
    colorInfo: 'var(--color-info-dark)',
    colorSuccess: 'var(--color-success-dark)',
    colorText: 'var(--color-black)',
    colorWarning: 'var(--color-warning-dark)',
    hoverBorderColor: 'var(--color-primary-20)',
  },
  InputNumber: {
    activeBorderColor: 'var(--color-secondary)',
    colorBorder: 'var(--color-primary)',
    colorBgContainer: 'var(--color-content-layout)',
    colorError: 'var(--color-error-dark)',
    colorInfo: 'var(--color-info-dark)',
    colorSuccess: 'var(--color-success-dark)',
    colorText: 'var(--color-black)',
    colorWarning: 'var(--color-warning-dark)',
    hoverBorderColor: 'var(--color-primary-20)',
  },
  Layout: {
    headerBg: 'var(--color-secondary)',
  },
  Menu: {
    itemSelectedColor: 'var(--color-info-dark)',
    itemBg: 'var(--color-primary-20)',
    subMenuItemBg: 'var(--color-primary-10)',
    darkItemBg: 'var(--color-primary)',
    darkSubMenuItemBg: 'var(--color-primary-60)',
    darkPopupBg: 'var(--color-primary-90)',
    darkItemSelectedBg: 'var(--color-secondary)',
    subMenuItemSelectedColor: 'var(--color-orange-dark)',
  },
  Pagination: {
    colorBgContainer: 'var(--color-content-layout)',
    colorBgTextHover: 'var(--color-primary-20)',
    colorBorder: 'var(--color-primary)',
    colorBorderSecondary: 'red',
    colorPrimary: 'var(--color-primary)',
    colorPrimaryHover: 'var(--color-primary-20)',
    colorText: 'var(--color-black)',
    itemActiveBg: 'var(--color-primary-10)',
    itemActiveColorDisabled: 'var(--color-black)',
    itemBg: 'transparent',
  },
  Radio: {
    colorBgContainer: 'transparent',
    colorText: 'var(--color-primary)',
    colorPrimary: 'var(--color-primary)',
    buttonCheckedColorDisabled: 'var(--color-gray)',
  },
  Select: {
    activeBorderColor: 'var(--color-secondary)',
    colorBorder: 'var(--color-primary)',
    colorError: 'var(--color-error-dark)',
    colorInfo: 'var(--color-info-dark)',
    colorSuccess: 'var(--color-success-dark)',
    colorText: 'var(--color-black)',
    colorWarning: 'var(--color-warning-dark)',
    hoverBorderColor: 'var(--color-primary-20)',
    selectorBg: 'var(--color-content-layout)',
  },
  Steps: {
    colorPrimary: 'var(--color-secondary)',
    colorText: 'var(--color-primary)',
    colorTextDescription: 'var(--color-gray)',
    controlItemBgActive: 'var(--color-secondary-20)',
  },
  Switch: {
    handleBg: 'var(--color-white)',
  },
  Table: {
    bodySortBg: 'var(--color-secondary-10)',
    colorBgContainer: 'var(--color-content-layout)',
    expandIconBg: 'var(--color-secondary-20)',
    headerBg: 'var(--color-primary-60)',
    headerColor: 'var(--color-white)',
    headerSortActiveBg: 'var(--color-secondary)',
    headerSortHoverBg: 'var(--color-primary-40)',
    rowHoverBg: 'var(--color-disabled-light)',
    rowSelectedBg: 'var(--color-secondary-10)',
    rowSelectedHoverBg: 'var(--color-disabled-light)',
  },
  Typography: {
    colorError: 'var(--color-error-dark)',
    colorInfo: 'var(--color-info-dark)',
    colorSuccess: 'var(--color-success-dark)',
    colorText: 'var(--color-black)',
    colorTextDisabled: 'var(--color-disabled-dark)',
    colorTextHeading: 'var(--color-primary)',
    colorTextSecondary: 'var(--color-gray)',
    colorWarning: 'var(--color-warning-dark)',
  },
} satisfies AntdComponents;
